version: '3.0'
services:
  rasa:
    image: rasa/rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
    extra_hosts:
       - "myhost:172.17.0.1"
  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      - redis-server --appendonly yes
